google/file.dart

CHANGELOG.md
lib/src/backends/chroot/chroot_file_system.dart
lib/src/backends/local.dart
lib/src/backends/local/local_file_system.dart
lib/src/backends/memory/memory_directory.dart
lib/src/backends/memory/memory_file_system.dart
lib/src/backends/memory/memory_file_system_entity.dart
lib/src/forwarding.dart
lib/src/forwarding/forwarding_file_system.dart
lib/src/interface.dart
lib/src/interface/file_system.dart
lib/src/io/shim_dart_io.dart
lib/src/io/shim_internal.dart
test/common_tests.dart

Remove `FileSystem.pathSeparator`, since it can now be expressed
as `fileSystem.path.separator`.
Fixes #9

Add `FileSystem.path`.

---

lib/src/backends/record_replay/common.dart
lib/src/backends/record_replay/encoding.dart
lib/src/backends/record_replay/events.dart
lib/src/backends/record_replay/mutable_recording.dart
lib/src/backends/record_replay/recording.dart
lib/src/backends/record_replay/recording_proxy_mixin.dart
lib/src/backends/record_replay/result_reference.dart
lib/src/testing/record_replay_matchers.dart
test/recording_test.dart

This introduces a level of indirection that will allow
recording objects to differentiate between the invocation
result return value, the recorded result value, and the
serialized result value.
This is used to provide "special handling" of certain
invocation results (such as byte arrays) to make recordings
more human-readable & editable.
This design also yields more technical correctness over
the previous design. This is because we used to delay
recording an invocation whose result was a Future until
that future completed. Now, we record the invocation
immediately and late-record future results (with support
for awaiting those futures when serializing a recoridng).
Another step in #11

Add ResultReference<T> to record_replay library.

---

lib/src/backends/record_replay/mutable_recording.dart
lib/src/backends/record_replay/recording_file.dart
lib/src/backends/record_replay/result_reference.dart
lib/src/testing/core_matchers.dart
pubspec.yaml
test/recording_test.dart

This uses the work that was done in #18 to wire up special
handling of certain file operations such that their results
will be written out to dedicated recording files.
(more work towards #11)

Serialize results of certain file invocations to separate file.

---

lib/src/backends/record_replay/encoding.dart
lib/src/backends/record_replay/recording_directory.dart
lib/src/backends/record_replay/recording_file.dart
lib/src/backends/record_replay/recording_file_system_entity.dart
lib/src/backends/record_replay/recording_link.dart
test/recording_test.dart

- use closures rather than subclasses to reduce some code in recording_file.dart
- `basename` and `dirname` were missing from `RecordingFileSystemEntity`
- `RecordingFileSystemEntity` didn't need to use two parameterized types.
That was an artifact of it having forked from `ForwardingFileSystemEntity`
- Change the name pattern of the blob files to use the basename of the
`RecordingFile` rather than the name of method being recorded

Clean up a few things in the record_replay library:

---

lib/src/backends/record_replay/encoding.dart
lib/src/backends/record_replay/events.dart
lib/src/backends/record_replay/mutable_recording.dart
lib/src/backends/record_replay/recording_file.dart
lib/src/backends/record_replay/result_reference.dart
test/recording_test.dart

This changes `encode()` to deeply encode the specified object
rather than performing a shallow encode. Previously, it relied
on `JSONEncoder` to do the work of walking the object graph and
calling `toEncodable` whenever it found a non-JSON type. Now,
callers can call `encode()` on the top-level object and get back
a deeply JSON-typed object that can be converted to JSON without
the need for a `toEncodable` callback.
This will be used during replay, when we'll compare an invocation
to the list of recorded invocations, each of which exists as a
JSON-type map.
Since we now control the encoding process entirely ourselves,
this also changes `encode()` to return `Future<dynamic>` rather than
`dynamic`, which in turn allows both `InvocationEvent.serialize()` and
`ResultReference.serializedValue` …

Deeply encode objects in `encode()`

---

lib/src/backends/record_replay/common.dart
lib/src/backends/record_replay/encoding.dart
lib/src/backends/record_replay/events.dart
lib/src/backends/record_replay/mutable_recording.dart
lib/src/backends/record_replay/recording_file.dart
lib/src/backends/record_replay/result_reference.dart

Doing so allows us to avoid dealing in futures all the way back
to `encode()`. This becomes important when implementing replay
since replay uses `noSuchMethod`, which can't await futures.
This also extracts out a few constants in preparation for their
use in replay.
Part of #11

Use synchronous file writing in BlobStreamReference

---

lib/record_replay.dart
lib/src/backends/record_replay/common.dart
lib/src/backends/record_replay/encoding.dart
lib/src/backends/record_replay/errors.dart
lib/src/backends/record_replay/proxy.dart
lib/src/backends/record_replay/recording.dart
lib/src/backends/record_replay/recording_file_system.dart
lib/src/backends/record_replay/recording_proxy_mixin.dart
lib/src/backends/record_replay/replay_directory.dart
lib/src/backends/record_replay/replay_file.dart
lib/src/backends/record_replay/replay_file_stat.dart
lib/src/backends/record_replay/replay_file_system.dart
lib/src/backends/record_replay/replay_file_system_entity.dart
lib/src/backends/record_replay/replay_link.dart
lib/src/backends/record_replay/replay_proxy_mixin.dart
lib/src/backends/record_replay/resurrectors.dart
lib/src/testing/record_replay_matchers.dart
test/replay_test.dart

This implements all the plumbing for `ReplayFileSystem` except
for the resurrectors for `FileSystemEntity`, `File`, `Directory`,
and `Link`. Those will land in a follow-on PR.
Part of #11

Partial implementation of ReplayFileSystem

---

lib/src/backends/record_replay/common.dart
lib/src/backends/record_replay/encoding.dart
lib/src/backends/record_replay/recording_file_system.dart
lib/src/backends/record_replay/recording_file_system_entity.dart
lib/src/backends/record_replay/recording_io_sink.dart
lib/src/backends/record_replay/recording_proxy_mixin.dart
lib/src/backends/record_replay/recording_random_access_file.dart
lib/src/backends/record_replay/replay_file_system.dart
lib/src/backends/record_replay/replay_proxy_mixin.dart
test/recording_test.dart

This lets us unify the identifier logic across record and replay
object serializations.
Part of #11

Extract out common `ReplayAware` interface

---

lib/src/backends/record_replay/proxy.dart
lib/src/backends/record_replay/recording_file_system.dart
lib/src/backends/record_replay/replay_file_system.dart
test/common_tests.dart

The ability to implement the `Function` interface has been
deprecated in the SDK. This change also adds dartdoc explaining
the implications of our use of `noSuchMethod` in the record_replay
library.

Remove 'implements Function' from MethodProxy

---

appvyor.yml

LocalFileSystem exposes a number of bugs in the Dart VM on Windows,
so for now we'll skip those, but this at least ensures that MemoryFileSystem
will have Windows testing, since it has no excuse to not run on Windows.
First step in #51

Enable Windows testing of MemoryFileSystem

---

test/common_tests.dart

This fixes the test failure in sdk 1.24.0.
@tvolkert

Make the test async so as to wait for write to be done

---

CHANGELOG.md
lib/src/backends/record_replay/codecs.dart
lib/src/backends/record_replay/replay_file.dart
pubspec.yaml

This fixes https://github.com/dart-lang/sdk/issues/28748 .
LineSplitter has been in an odd state for a while where it implements Converter in Dart 1.0 but not in 2.0.  We've made the change in the Dart 2.0 repository to flip it entirely away from Converter.  This adds a wrapper implementation that satisfies the Converter interface.

Fix line splitter

---

lib/src/backends/memory/memory_directory.dart
lib/src/backends/memory/memory_file_system_entity.dart

Fixes #65.
In the first commit of PR #63, I think analyzer should have warned me that the `_RenameOverwriteValidator<_DirectoryNode>` callback was being passed a `_Node`, but it didn't! https://github.com/dart-lang/sdk/issues/31410 I think. [simplified dartpad](https://dartpad.dartlang.org/adc68f958ebb8d3ec8bef1d1f01a4812)
The alternative to this fix is type-annotating `_renameSync` with a T, and declaring `validateOverwriteExistingEntity` to be a `_RenameOverwriteValidator<T>`.

Fix impl of memory directory's _renameSync.

---

pubspec.yaml

This drops '-dev.infinity' from sdk constraint, which seems to be per outdated guidelines.
Besides it prevents use of the package with 'edge'-based dart sdk.

Update sdk constraint to <2.0.0. 

---

.travis.yml

Only marks the build red if stable fails.

Allow dev to fail on travis

---

lib/src/forwarding/forwarding_directory.dart

Due to an upcoming change in Dart 2.0
(https://github.com/dart-lang/sdk/issues/32148), it will no longer be
allowed for a class to implement the same generic interface in
different ways.  (E.g. a class cannot implement/extend/mixin both
A<int> and A<String>).
This causes problems with _LocalDirectory.  It extends
_LocalFileSystemEntity<_LocalDirectory, Directory>, which extends
ForwardingFileSystemEntity<_LocalDirectory, Directory>, but it mixes
in ForwardingDirectory, which extends
ForwardingFileSystemEntity<Directory, io.Directory>.
The solution is to make ForwardingDirectory a generic mixin, with
ForwardingDirectory<T> extending ForwardingFileSystemEntity<T,
io.Directory>.  Type inference automatically fills in the type
argument T=_LocalDirectory at the site of the declaration of …

Make ForwardingDirectory generic.

---

packages/file/lib/src/backends/record_replay/recording_proxy_mixin.dart
packages/file/lib/src/backends/record_replay/result_reference.dart
packages/file/test/recording_test.dart

Fixes #84 
There were a number of runtime failures. Some were simple. The ones that involved noSuchMethod in `recording_proxy_mixin.dart` were not simple. Basically, because of how the `noSuchMethod` is implemented, in terms of Futures and Streams, and how FutureReference.value and StreamReference.value work, types were being lost. If `value`  was a `Future<Directory>`, as returned by `Function.apply`, then `result` was inevitably `Future<dynamic>` by the end of `noSuchMethod`. ☹️ 
Tested with `dart --preview-dart-2 test/recording_test.dart` and `dart test/recording_test.dart`.

Fix runtime errors in recording_test

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/record_replay/recording_proxy_mixin.dart

This is not the last fix for Dart 2 runtime mode, so I don't recommend releasing yet.

Fix for Dart 2 runtime + 2.0.0-dev.61.0

---

packages/file/lib/src/interface/error_codes.dart

When using this library in an operating system that is not Linux, MacOS or Windows (such as Android or iOS), there is a crash when getting a file system error code.
A possible solution is to use Linux as a fallback whenever the OS doesn't have its own error code defined.

Use Linux error codes as fallback when OS error codes are not defined

---

packages/file/test/common_tests.dart

Failing tests due to #112.
I couldn't figure out how to mark them as failing (or skip) since there's no `@failingTest` and the `test` function seems custom.
@tvolkert

Add tests that fail because of slash directions

---

packages/file/lib/src/forwarding/forwarding_directory.dart
packages/file/lib/src/forwarding/forwarding_file.dart
packages/file/lib/src/forwarding/forwarding_link.dart

The ability for a class extending non-Object to be used as a mixin
will be removed from Dart in an upcoming release.  In general, code
taking advantage of this ability can be fixed in two ways:
- The class can be changed to use the new "mixin" syntax (see
https://github.com/dart-lang/language/blob/master/working/0006.%20Superinvocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md).
- If the class contains no references to "super", the base class can
simply be moved into the "implements" clause (e.g. "abstract class M
extends A implements B {...}" can be changed to "abstract class M
implements A, B {...}"
This CL adopts the second strategy, since it's feasible (the classes
in question do not use "super") and since it's backwards compatible to
older versions of Dart.

Rework mixins to avoid extending non-Object.

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/record_replay/recording_file_system_entity.dart
packages/file/lib/src/backends/record_replay/recording_proxy_mixin.dart
packages/file/lib/src/backends/record_replay/replay_io_sink.dart
packages/file/lib/src/backends/record_replay/replay_proxy_mixin.dart
packages/file/pubspec.yaml

The ability for a class used as a mixin to call super has been removed
from Dart, but due to an analyzer bug some usages slipped through the
cracks.  The analyzer bug has now been fixed, so we need a
corresponding fix to package:file.
The solution is to change the mixin classes to use the new "mixin"
syntax.

Switch to new-style mixins so that super.noSuchMethod can be called.

---

packages/file_testing/CHANGELOG.md
packages/file_testing/lib/src/testing/core_matchers.dart
packages/file_testing/pubspec.yaml

This will get rid of transitive dep on test package for flutter_tools.
I also updated some deprecated member use and some various style stuff from Flutter's analysis options - I was going to do that for the file package as well but that's a bigger chore.  If we'd rather have it all in one PR I can do that though.
/cc @jonahwilliams @tvolkert

Use test_api instead of test

---

packages/file/test/common_tests.dart

Context: https://github.com/google/file.dart/issues/112

Adds `skip` to common_tests.dart `test` function. Uses it for failing tests.

---

packages/file/lib/src/forwarding/forwarding_file.dart
packages/file/pubspec.yaml

An upcoming change to the Dart SDK will change the signature
of `File.openRead()` from returning `Stream<List<int>>` to
returning `Stream<Uint8List>`.
This forwards-compatible change prepares for that SDK breaking
change by casting the Stream to `List<int>` before transforming
it.
https://github.com/dart-lang/sdk/issues/36900

Prepare for upcoming change to File.openRead()

---

packages/file/lib/src/backends/memory/node.dart

Add a dartdoc comment for `RealNode.clock` to quiet an analysis
complaint.

Add a dartdoc comment for RealNode.clock

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/memory/memory_file.dart
packages/file/lib/src/backends/memory/memory_random_access_file.dart
packages/file/lib/src/backends/memory/node.dart
packages/file/pubspec.yaml
packages/file/test/common_tests.dart
packages/file/test/memory_test.dart

Add a basic implementation for `MemoryRandomAccessFile` so that
`MemoryFile.open`/`openSync` can work.  Currently all functions
related to `lock`/`unlock` remain unimplemented.
Fixes https://github.com/google/file.dart/issues/7.

Add a basic implementation for MemoryRandomAccessFile

---

packages/file/test/common_tests.dart

The suite of common tests repeatedly opens `IOSink`s and
`StreamController`s but closed them only the first time.  I don't
definitively know that this was the cause for many of the test flakes
related to local filesystems, but with this change, I haven't hit
file-not-found flakes locally after several hundred iterations of
running `chroot_test.dart`.

Try to fix some flaky tests

---

analysis_options.yaml
packages/file/lib/src/backends/memory/memory_file.dart
packages/file/lib/src/backends/memory/memory_random_access_file.dart
packages/file/lib/src/backends/record_replay/proxy.dart
packages/file/test/chroot_test.dart
packages/file/test/common_tests.dart
packages/file/test/local_test.dart
packages/file/test/replay_test.dart

Remove some TODOs that depended on Dart SDK issues that have since
been fixed.
* Re-enable a test that attempts writing after the `IOSink` is
closed.
* Enable various other skipped tests.
* Remove `_MethodInvocationProxy`.
Also add some GitHub issue references for some TODOs that I added
earlier.

Remove some stale TODOs

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/memory/memory_directory.dart
packages/file/pubspec.yaml
packages/file/test/memory_test.dart

Currently the memory file system uses a static to track unique names for the system temp directory. This causes tests that make assertions about created directories to only work in a particular order, even if the file system instance is not shared.
Updates the static to an Expando, which performs the same logic but per-instance.

Per instance temp directory naming

---

packages/file/lib/src/backends/record_replay/codecs.dart
packages/file/lib/src/backends/record_replay/replay_file.dart

`Uint8List` is already a `List<int>`; we don't need a `Converter` to
go from one type to the other and can cast instead.

Remove Uint8ListToPlainList

---

packages/file/lib/src/backends/record_replay/common.dart
packages/file/lib/src/backends/record_replay/errors.dart
packages/file/test/replay_test.dart

1. `NoMatchingInvocation.toString()` attempted to avoid printing a
comma after the last argument, but the code was backwards, instead
adding a trailing comma and omitting the comma after the first
argument.  Move the code to print the comma to the beginning of
the loop iteration; this also matches handling of named arguments.
2. Break up `NoMatchingInvocationError.toString()` so that we can
generate human-readable string representations of `Invocation`s
elsewhere for debugging.

Fix and refactor NoMatchingInvocationError.toString()

---

packages/file/CHANGELOG.md
packages/file/test/common_tests.dart
packages/file/test/utils.dart
packages/file/test/utils_test.dart

There seems to be an underlying Dart issue that causes access and
modification times to files to sometimes be 1 second before the
current time.
Adjust `package:file`'s access and modification time tests to
tolerate this.  Previously they verified that the access and
modification times always were within a 1 second interval, starting
from the current second and ending at the next second.  This change
adjusts the interval to start at the previous second and end at the
current time rounded up to the nearest second.  This means that the
interval will be 1 second if the current time happens to be an exact
second or will be up to 2 seconds otherwise.
With this change, I've run one of the modification time tests in a
continuous loop for 10s (>300K iterations) without failure.
Bonus: Make some …

Try to fix flaky timestamp tests

---

packages/file/CHANGELOG.md
packages/file/pubspec.yaml

Some of my earlier commits didn't make the cutoff for 5.2.1.  Adjust
CHANGELOG.md accordingly.

Fix CHANGELOG.md and update package version

---

packages/file/test/chroot_test.dart
packages/file/test/common_tests.dart

Use the `exists` `Matcher` instead of `existsSync()` in tests.
Mechanical change to replace:
expect(f.existsSync(), true);
expect(f.existsSync(), isTrue);
and
expect(g.existsSync(), false);
expect(g.existsSync(), isFalse);
with
expect(f, exists);
expect(g, isNot(exists));

Replace existsSync() usage in tests

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/memory/memory_file.dart
packages/file/lib/src/backends/memory/memory_random_access_file.dart
packages/file/lib/src/backends/record_replay/common.dart
packages/file/test/chroot_test.dart
packages/file/test/common_tests.dart
packages/file/test/local_test.dart
packages/file/test/replay_test.dart

Fix `MemoryRandomAccessFile` to use only its `FileNode` and never the
corresponding `MemoryFile`.  While the `MemoryRandomAccessFile` (the
equivalent of a file handle) is open, its `FileNode` should never
change, but the original `MemoryFile` might become backed by a
different node if the file is moved, removed, or replaced.
POSIX systems typically allow this; Windows typically doesn't.  For
now, make `MemoryFileSystem` follow the typical POSIX behavior. (In
the long-term, `MemoryFileSystem` perhaps should have configurable
behavior.)
Similarly, make `MemoryFile.openWrite`'s `IOSink` resolve the
`FileNode` immediately instead of adding it to an async queue.
Otherwise node resolution could return a different `FileNode` than
what was originally intended.
Eagerly resolving the `FileNode` has …

Make MemoryRandomAccessFile handle the file being moved from under it

---

packages/file/CHANGELOG.md
packages/file/lib/src/forwarding/forwarding_file.dart
packages/file/pubspec.yaml

`ForwardingFile.openRead` was changed to return a `Stream<Uint8List>`
instead of a `Stream<List<int>>` in preparation for making a
corresponding change to `dart:io`.  However, that `dart:io` change
caused more breakage than expected and was reverted without making
corresponding reverts to `package:file`.  I don't think that it makes
sense for `ForwardingFile` to return something different than its
delegate.
Without this change, the following code will fail with `package:file`
but not with `dart:io`:
```dart
await someFile.openRead().transform(utf8.decoder);
```
and unintuitively requires adding `.cast<List<int>>()` before
the transformation.
Bonus cleanup: since dart:io's `File.readAsBytes`/`readAsBytesSync`
are declared to return `Uint8List`, `ForwardingFile` should no longer
need to …

Make ForwardingFile.openRead return Stream<List<int>> again

---

packages/file/lib/src/backends/chroot.dart
packages/file/lib/src/backends/local/local_file_system.dart
packages/file/lib/src/backends/memory/memory_directory.dart
packages/file/lib/src/backends/memory/memory_file_system.dart
packages/file/lib/src/backends/memory/memory_file_system_entity.dart
packages/file/lib/src/backends/memory/memory_link.dart
packages/file/lib/src/forwarding/forwarding_directory.dart
packages/file/lib/src/forwarding/forwarding_file.dart
packages/file/lib/src/forwarding/forwarding_file_system.dart
packages/file/lib/src/forwarding/forwarding_file_system_entity.dart
packages/file/lib/src/forwarding/forwarding_link.dart
packages/file/lib/src/interface/directory.dart
packages/file/lib/src/interface/file.dart
packages/file/lib/src/interface/file_system.dart
packages/file/lib/src/interface/file_system_entity.dart
packages/file/lib/src/interface/link.dart

Since this package doesn't support Dart 2.0, Future/Stream are always
exported from dart:core.

Remove unused dart:async imports.

---

packages/file/lib/src/backends/chroot.dart
packages/file/lib/src/backends/chroot/chroot_file.dart
packages/file/lib/src/backends/chroot/chroot_random_access_file.dart
packages/file/lib/src/forwarding.dart
packages/file/lib/src/forwarding/forwarding_random_access_file.dart

`ChrootFile.open`/`ChrootFile.openSync` previously returned the
delegate's `RandomAccessFile` directly.  However, `RandomAccessFile`
has a `path` property (sigh) that exposes the underlying path instead
of the chroot'd path.
Add delegating wrapper classes for `RandomAccessFile` so that we can
override the returned `path`.

Add _ChrootRandomAccessFile and ForwardingRandomAccessFile

---

packages/file_testing/CHANGELOG.md
packages/file_testing/lib/src/testing/core_matchers.dart
packages/file_testing/lib/src/testing/internal.dart
packages/file_testing/pubspec.yaml

As it says. no changes, but removed extra usage of meta

migrate file_testing to null safety

---

packages/file/CHANGELOG.md
packages/file/lib/memory.dart
packages/file/lib/src/backends/memory/memory_directory.dart
packages/file/lib/src/backends/memory/memory_file.dart
packages/file/lib/src/backends/memory/memory_file_system.dart
packages/file/lib/src/backends/memory/memory_file_system_entity.dart
packages/file/lib/src/backends/memory/memory_link.dart
packages/file/lib/src/backends/memory/node.dart
packages/file/lib/src/backends/memory/operations.dart
packages/file/pubspec.yaml
packages/file/test/memory_operations_test.dart
packages/file/test/memory_test.dart

Example usage is documented in the list test cases. Also fix the case where decoding errors do not match LocalFIleSystem behavior.

Add an operation handle to allow inserting FileSystemExceptions in the memory fs without mocking

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/memory/memory_directory.dart
packages/file/lib/src/backends/memory/memory_file.dart
packages/file/lib/src/backends/memory/memory_link.dart
packages/file/lib/src/backends/memory/operations.dart
packages/file/pubspec.yaml
packages/file/test/memory_operations_test.dart

Can remove most of the rest of error_handling_io's mocks

Add ophandle for FileSystemEntity.exists/existsSync

---

packages/file/CHANGELOG.md
packages/file/lib/src/interface/file_system.dart
packages/file/pubspec.yaml
packages/file/test/common_tests.dart

`FileSystem.isLink` called `FileSystem.type` with the default argument of `followLinks: true`.  This is obviously wrong since it would mean that `isLink` would never return true (except maybe for broken symbolic links).
Make `FileSystem.isLink` use `followLinks: false`.  This is what `dart:io`'s `FileSystemEntity.isLink` is documented to do.
Partially addresses https://github.com/google/file.dart/issues/8.

Make `FileSystem.isLink` actually work

---

packages/file/CHANGELOG.md
packages/file/lib/src/backends/memory/memory_file_system.dart
packages/file/pubspec.yaml
packages/file/test/common_tests.dart

`_MemoryFileSystem.findNode` returns `reference?.directory` if given the root path or an empty path.  However, an empty path should be treated as non-existent, not as a directory.  Instead explicitly return `null` as a special case when given an empty path.
Partially addresses https://github.com/google/file.dart/issues/198.

Fix MemoryFileSystem to treat an empty path as non-existent

---

packages/file/lib/src/backends/memory/memory_file.dart
packages/file/test/memory_test.dart

Route stream errors to the stream completer rather than the file completer.
Fixes #219

MemoryFileSystem addStream onError

---

packages/file_testing/CHANGELOG.md
packages/file_testing/pubspec.yaml

This was required until `package:glob` supported `package:file` v7, which happened in glob 2.1.2: https://pub.dev/packages/glob/changelog#212

Remove now unnecessary glob dependency override
